/*
  Warnings:

  - The values [LUBRIFICACAO_ROLAMENTOS,FILTRO_SUCCAO_ASPERSAO,FILTRO_DUTO_FORNECIMENTO,INSPECAO_ALETAS_TROCADOR,MANUTENCAO_VENTILADOR_TORRE,VERIFICACAO_QUADRO_CONTROLE,INSPECAO_NIVEL_TANQUE_CONTAINER,INSPECAO_NIVEL_TANQUE_TORRE,REGISTRO_TEMPERATURA_PRESSAO,FILTRO_Y_REPOSICAO,INSPECAO_VAZAMENTOS_TUBULACAO,TESTE_PH_FLUIDO,INSPECAO_ELETRICA_QCP,DRENAGEM_TOPO_TORRE,SUBSTITUICAO_FLUIDO_REFRIGERANTE,INSPECAO_ANUAL_GERAL] on the enum `TipoAtividade` will be removed. If these variants are still used in the database, this will fail.

*/
-- CreateEnum
CREATE TYPE "StatusChecklistItem" AS ENUM ('PENDENTE', 'OK', 'NAO_APLICAVEL', 'REQUER_ATENCAO');

-- AlterEnum
BEGIN;
CREATE TYPE "TipoAtividade_new" AS ENUM ('MANUTENCAO_PREVENTIVA_GERAL', 'FALHA_ENERGIA', 'FALHA_BOMBA_CIRCULACAO', 'FALHA_VENTILADOR_EXAUSTAO', 'FALHA_BOMBA_REPOSICAO', 'ALARME_VAZAMENTO', 'ALARME_ALTA_TEMPERATURA', 'ALARME_ALTA_PRESSAO', 'ALARME_BAIXA_PRESSAO', 'ALARME_BAIXA_VAZAO', 'ALARME_CONDENSACAO', 'FALHA_VEDACAO_BOMBA', 'FALHA_VENTILADOR_TORRE', 'SUBSTITUICAO_VALVULA_EXAUSTAO', 'SUBSTITUICAO_VENTILADOR_TORRE', 'OUTRO');
ALTER TABLE "ordens_servico" ALTER COLUMN "tipoAtividade" TYPE "TipoAtividade_new" USING ("tipoAtividade"::text::"TipoAtividade_new");
ALTER TYPE "TipoAtividade" RENAME TO "TipoAtividade_old";
ALTER TYPE "TipoAtividade_new" RENAME TO "TipoAtividade";
DROP TYPE "public"."TipoAtividade_old";
COMMIT;

-- CreateTable
CREATE TABLE "checklist_items_os" (
    "id" TEXT NOT NULL,
    "osId" TEXT NOT NULL,
    "itemId" TEXT NOT NULL,
    "descricao" TEXT NOT NULL,
    "periodicidade" TEXT NOT NULL,
    "subsistema" TEXT NOT NULL,
    "referencia" TEXT NOT NULL,
    "status" "StatusChecklistItem" NOT NULL DEFAULT 'PENDENTE',
    "observacao" TEXT,
    "atualizadoPorId" TEXT,
    "atualizadoEm" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "checklist_items_os_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "checklist_items_os" ADD CONSTRAINT "checklist_items_os_osId_fkey" FOREIGN KEY ("osId") REFERENCES "ordens_servico"("id") ON DELETE CASCADE ON UPDATE CASCADE;
